version: '2'
services:
    jhipsta-app:
        image: jhipsta-app
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsta-postgresql:5432/jhipsta
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsta-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsta-postgresql
